# Generated by Django 2.0 on 2018-04-22 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0008_auto_20180403_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('item_code', models.CharField(max_length=48)),
                ('description', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='ItemUom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack', models.IntegerField()),
                ('pack_type', models.IntegerField(choices=[(1, 'Case')])),
                ('upc', models.CharField(max_length=16)),
                ('sku', models.CharField(max_length=32)),
                ('weight_eng', models.FloatField()),
                ('length_eng', models.FloatField()),
                ('width_eng', models.FloatField()),
                ('height_eng', models.FloatField()),
                ('weight_metric', models.FloatField()),
                ('length_metric', models.FloatField()),
                ('width_metric', models.FloatField()),
                ('height_metric', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Item')),
            ],
        ),
    ]
