# Generated by Django 2.0 on 2018-04-25 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='itemuom',
            name='pack_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.ItemPack'),
        ),
    ]
