# Generated by Django 2.0 on 2018-04-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20180425_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemuom',
            name='height_eng',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='itemuom',
            name='height_metric',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='itemuom',
            name='length_eng',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='itemuom',
            name='length_metric',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='itemuom',
            name='weight_eng',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='itemuom',
            name='weight_metric',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='itemuom',
            name='width_eng',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='itemuom',
            name='width_metric',
            field=models.FloatField(default=0.0),
        ),
    ]
