# Generated by Django 2.0 on 2018-04-30 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180403_2229'),
        ('item', '0004_auto_20180430_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Organization'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('organization', 'item_code')},
        ),
    ]
