# Generated by Django 2.0 on 2018-03-09 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiving', models.CharField(choices=[('0', '0'), ('R', 'R'), ('RW', 'RW')], default='0', max_length=5)),
                ('shipping', models.CharField(choices=[('0', '0'), ('R', 'R'), ('RW', 'RW')], default='0', max_length=5)),
                ('mobile', models.CharField(choices=[('0', '0'), ('R', 'R'), ('RW', 'RW')], default='0', max_length=5)),
                ('inventory', models.CharField(choices=[('0', '0'), ('R', 'R'), ('RW', 'RW')], default='0', max_length=5)),
                ('items', models.CharField(choices=[('0', '0'), ('R', 'R'), ('RW', 'RW')], default='0', max_length=5)),
                ('reports', models.CharField(choices=[('0', '0'), ('R', 'R'), ('RW', 'RW')], default='0', max_length=5)),
                ('organization', models.CharField(choices=[('0', '0'), ('R', 'R'), ('RW', 'RW')], default='0', max_length=5)),
                ('security', models.CharField(choices=[('0', '0'), ('R', 'R'), ('RW', 'RW')], default='0', max_length=5)),
                ('client', models.CharField(choices=[('0', '0'), ('R', 'R'), ('RW', 'RW')], default='0', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('admin', 'Admin User'), ('manager', 'Manager User'), ('assistant', 'Assistant User'), ('regular', 'Regular User'), ('client', 'Client User')], default='regular', max_length=20)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='groupaccess',
            name='user_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserGroup'),
        ),
    ]
