# Generated by Django 2.0 on 2018-03-09 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergroup',
            old_name='user',
            new_name='users',
        ),
    ]
