# Generated by Django 2.0 on 2018-03-22 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180313_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupaccess',
            name='user_group',
            field=models.ForeignKey(db_column='app_user_group_link', on_delete=django.db.models.deletion.CASCADE, to='app.UserGroup'),
        ),
        migrations.AlterModelTable(
            name='groupaccess',
            table='app_user_group_access',
        ),
        migrations.AlterModelTable(
            name='usergroup',
            table='app_user_group',
        ),
    ]
