# Generated by Django 2.0 on 2018-03-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180322_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(max_length=16)),
                ('active', models.BooleanField(default=False)),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Client'), (2, 'Customer'), (3, 'Carrier')])),
                ('description', models.TextField()),
                ('mt_address1', models.CharField(max_length=64)),
                ('mt_address2', models.CharField(blank=True, max_length=64, null=True)),
                ('mt_address3', models.CharField(blank=True, max_length=64, null=True)),
                ('mt_city', models.CharField(max_length=64)),
                ('mt_state', models.CharField(max_length=16)),
                ('mt_zip', models.CharField(max_length=16)),
                ('mt_country', models.CharField(max_length=64)),
                ('st_address1', models.CharField(max_length=64)),
                ('st_address2', models.CharField(blank=True, max_length=64, null=True)),
                ('st_address3', models.CharField(blank=True, max_length=64, null=True)),
                ('st_city', models.CharField(max_length=64)),
                ('st_state', models.CharField(max_length=16)),
                ('st_zip', models.CharField(max_length=16)),
                ('st_country', models.CharField(max_length=64)),
            ],
        ),
    ]
