# Generated by Django 2.0 on 2018-04-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180403_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_id',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
