# Generated by Django 2.0 on 2018-05-22 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0008_auto_20180403_2229'),
        ('item', '0008_auto_20180503_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.IntegerField()),
                ('ref_no', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('expected_arrival_date', models.DateField()),
                ('actual_arrival_date', models.DateField(blank=True, null=True)),
                ('receive_start_date', models.DateField(blank=True, null=True)),
                ('receive_finish_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField(default=1)),
                ('weight', models.FloatField(default=0.0)),
                ('item_udf1', models.CharField(max_length=32)),
                ('item_udf2', models.CharField(max_length=32)),
                ('quantity_requested', models.IntegerField(default=1)),
                ('quantity_received', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Item')),
                ('itemuom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.ItemUom')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receive.Order')),
            ],
        ),
    ]
