# Generated by Django 2.0 on 2018-05-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('wip', 'Wip'), ('hold', 'Hold'), ('receive', 'Receive'), ('closed', 'Closed'), ('invoiced', 'Invoiced'), ('cancelled', 'Cancelled')], default='open', max_length=10),
        ),
    ]
