# Generated by Django 2.0 on 2018-05-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receive', '0002_auto_20180523_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.IntegerField(unique=True),
        ),
    ]
