# Generated by Django 2.0 on 2018-05-26 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180403_2229'),
        ('receive', '0004_auto_20180526_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_carrier', to='app.Organization'),
        ),
        migrations.AddField(
            model_name='order',
            name='container',
            field=models.CharField(default='', max_length=50),
        ),
    ]
