# Generated by Django 2.0 on 2018-05-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receive', '0005_auto_20180526_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='item_udf1',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='item_udf2',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='quantity_received',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='quantity_requested',
            field=models.IntegerField(default=0),
        ),
    ]
