# Generated by Django 2.0 on 2018-06-05 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180403_2229'),
        ('receive', '0006_auto_20180526_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='organization_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_customer_org', to='app.Organization'),
        ),
        migrations.AddField(
            model_name='order',
            name='ponumber',
            field=models.CharField(default='', max_length=32),
        ),
    ]
