# Generated by Django 2.0 on 2018-06-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receive', '0009_auto_20180611_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
